*** Keywords ***
# v_AllTodosDisplayed
#     [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
#     Log To Console    To be implemented
#     Log    ${numOpenTodos}
#     Log    ${numCompletedTodos}
v_ActiveTodosDisplayed
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
v_CompletedTodosDisplayed
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
e_addTodo
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
e_completeTodo
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
e_deleteCompletedTodo
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
e_clearCompletedTodos
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
e_editOpenTodo
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
e_showActiveOnly
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
e_showAll
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
e_deleteOpenTodo
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
e_editCompletedTodo
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
e_showCompletedOnly
    [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
    Log To Console    To be implemented
    Log    ${numOpenTodos}
    Log    ${numCompletedTodos}
# e_reopenTodo
#     [Arguments]    ${numOpenTodos}=${None}    ${numCompletedTodos}=${None}
#     Log To Console    To be implemented
#     Log    ${numOpenTodos}
#     Log    ${numCompletedTodos}